### ISSUE TITLE
Problem with `require "bundler/setup"`

### ISSUE THREAD

**Issue by jbodah** [jbodah/test_server_rb#10]
```
jbodah r2.5.0 ~/repos/sanity (master) $ test_server --test test/sanity_test.rb
Traceback (most recent call last):
        21: from /usr/local/bin/test_server:23:in `<main>'
        20: from /usr/local/bin/test_server:23:in `load'
        19: from /usr/local/lib/ruby/gems/2.5.0/gems/test_server_rb-1.0.1/exe/test_server:4:in `<top (required)>'
        18: from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        17: from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        16: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/setup.rb:10:in `<top (required)>'
        15: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler.rb:101:in `setup'
        14: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler.rb:135:in `definition'
        13: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/definition.rb:35:in `build'
        12: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/dsl.rb:13:in `evaluate'
        11: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/dsl.rb:218:in `to_definition'
        10: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/dsl.rb:218:in `new'
         9: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/definition.rb:120:in `initialize'
         8: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/definition.rb:618:in `converge_paths'
         7: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/definition.rb:618:in `any?'
         6: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/definition.rb:619:in `block in converge_paths'
         5: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/definition.rb:575:in `specs_changed?'
         4: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/definition.rb:590:in `specs_for_source_changed?'
         3: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/source/path.rb:108:in `specs'
         2: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/source/path.rb:100:in `local_specs'
         1: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/source/path.rb:165:in `load_spec_files'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/source/path.rb:165:in `[]': Operation not supported on socket - /Users/jbodah/repos/sanity/test.sock (Errno::EOPNOTSUPP)
```

**Comment by jbodah** [comment]
Fixed
